name:                rabbitly
version:             0.1.0.0
github:              "jac3km4/rabbitly"
license:             BSD3
author:              "jac3km4"
maintainer:          "jac3km4@gmail.com"
copyright:           "2020 jac3km4"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jac3km4/rabbitly#readme>

default-extensions:
- OverloadedStrings
- NamedFieldPuns
- LambdaCase

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - containers >= 0.6
  - unordered-containers >= 0.2
  - mtl >= 2.2
  - exceptions >= 0.10
  - bytestring >= 0.10
  - bytestring-strict-builder >= 0.4
  - text >= 1.2
  - network >= 3.1
  - cereal >= 0.5
  - streamly >= 0.7.2
  - streamly-bytestring >= 0.1

executables:
  rabbitly-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rabbitly
    - streamly >= 0.7.2

tests:
  rabbitly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rabbitly
    - tasty
    - tasty-hedgehog
    - hedgehog
    - cereal
    - unordered-containers
    - bytestring
